version: "3.8"

services:
  miniconda:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
    - ".:/spruce"
    - "C:/Program Files/Lumerical/v221/api/python:/opt/lumerical/v221/api/python"
    container_name: lumerical
    ports:
    - "8888:8888"
    expose:
      - "8888"
    stdin_open: true
    tty: true